import { Injectable } from '@angular/core';
import { Category } from '../models/category.model';
import { Product } from '../models/product.model';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  private categories: Category[] = [
    { id: 1, name: 'SkullPanda' },
    { id: 2, name: 'Hirono' },
    { id: 3, name: 'Crybaby' },
    { id: 4, name: 'Other' },
    { id: 5, name: 'Anime'},
    { id: 6, name: 'Labubu'},
    { id: 7, name: 'LOL'}
  ];

  private products: Product[] = [
    {
    id: 1,
    name: 'SkullPanda Winter Symphony Series',
    description: 'SkullPanda Winter Symphony Series - это коллекционная фигурка, которая является частью серии SkullPanda. Она выполнена в виде милого пандочки, одетого в зимнюю одежду и украшенного снежинками. Фигурка изготовлена из высококачественного материала и имеет детализированную окраску, что делает ее привлекательной для коллекционеров и любителей уникальных игрушек.',
    categoryId: 1,
    price: 3990,
    rating: 4.8,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p10/p7e/57884416.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/p10/p7e/57884416.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pa7/p7a/57884417.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p3d/p77/57884418.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pd3/p73/57884419.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/pop-mart-pop-mart-skullpanda-winter-symphony-series-13-5-sm-1-sht-143895400/?c=750000000',
    likes: 0,
  },
  {
    id:2,
    name: 'Wild Magic Tarot Blind Box',
    description: 'Wild Magic Tarot Blind Box - это коробка сюрприз с фигурками и картами Таро. Внутри коробки содержится случайная карта Таро и фигурка из серии Wild Magic. Коробка изготовлена из высококачественного материала и имеет яркую упаковку, что делает ее привлекательной для коллекционеров и любителей уникальных игрушек.',
    categoryId: 4,
    price: 13000,
    rating: 4.5,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/pf4/p86/93731489.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/pf4/p86/93731489.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pde/p3b/93731490.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p75/p38/93731491.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/wild-magic-tarot-blind-box-korobka-sjurpriz-s-figurkami-i-kartoi-taro-9-sm-1-sht-154203287/?c=750000000',
    likes: 0,
  },
  {
    id:3,
    name: 'Brelok Magicheskaja Bitva',
    description: 'Brelok Magicheskaja Bitva - это стильный брелок, который может быть использован как элемент декора или аксессуар. Брелок изготовлен из высококачественного материала и имеет яркий дизайн, что делает его привлекательным для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 5,
    price: 8000,
    rating: 4.2,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p4b/p43/69092413.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/p4b/p43/69092413.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pe1/p3f/69092414.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p78/p3c/69092415.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p0e/p39/69092416.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p43/p1c/69092420.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/brelok-magicheskaja-bitva-14-sm-mul-tikolor-146929129/?c=750000000',
    likes: 0,
  },
  {
    id:4,
    name: 'Igrushka Podveska Pop Mart Hacipupu',
    description: 'Igrushka Podveska Pop Mart Hacipupu - это стильная подвеска, которая может быть использована как элемент декора или аксессуар. Подвеска изготовлена из высококачественного материала и имеет яркий дизайн, что делает ее привлекательной для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 4,
    price: 1529,
    rating: 5,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/paa/p02/56643790.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/pbe/p00/56643791.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pe1/p3f/69092414.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p28/p04/56643792.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/igrushka-podveska-pop-mart-hacipupu-13-sm-mul-tikolor-143547315/?c=750000000',
    likes: 0,
  },
  {
    id:5,
    name: 'Pop Mart Hironole Petit Prince Series',
    description: 'Pop Mart Hironole Petit Prince Series - это коллекционная серия фигурок, вдохновленная классическим произведением Антуана де Сент-Экзюпери. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 2,
    price: 14990,
    rating: 5,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p40/p58/70699847.png?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/p5c/p58/70699848.png?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pe4/p5a/70699850.png?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pc6/p5b/70699858.png?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/pop-mart-hironole-petit-prince-series-figures-11-sm-1-sht-147438560/?c=750000000',
    likes: 0,
  },
  {
    id:6,
    name: 'Pop Mart Skullpanda The Warmth',
    description: 'Pop Mart Skullpanda The Warmth - это коллекционная фигурка, которая является частью серии SkullPanda. Она выполнена в виде милого пандочки, одетого в теплую одежду и украшенного снежинками. Фигурка изготовлена из высококачественного материала и имеет детализированную окраску, что делает ее привлекательной для коллекционеров и любителей уникальных игрушек.',  
    categoryId: 1,
    price: 3700,
    rating: 5,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p8c/p75/76250506.jpg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/p68/p78/76250511.jpg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p85/p78/76250512.jpg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pc4/p75/76250508.jpg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/pop-mart-skullpanda-the-warmth-8-sm-1-sht-149092131/?c=750000000',
    likes: 0,
  },
  {
    id:7,
    name: 'Pop Mart hirono',
    description: 'Pop Mart hirono - это коллекционная фигурка, которая является частью серии Pop Mart. Она выполнена в виде милого зверька, одетого в теплую одежду и украшенного снежинками. Фигурка изготовлена из высококачественного материала и имеет детализированную окраску, что делает ее привлекательной для коллекционеров и любителей уникальных игрушек.',  
    categoryId: 2,
    price: 14500,
    rating: 5,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p46/p23/51838049.png?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/pce/p25/51838051.png?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p06/p26/51838053.png?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p3f/p26/51838055.png?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/figurka-pop-mart-hirono-10-3-sm-1-sht-120978316/?c=750000000',
    likes: 0,
  },
  {
    id:8,
    name: 'Zootopia Zveropolis',
    description: 'Zootopia Zveropolis 15 sm Multikolor - это коллекционная фигурка, которая является частью серии Zootopia. Она выполнена в виде милого зверька из города Зверополиса, одетого в теплую одежду и украшенного снежинками. Фигурка изготовлена из высококачественного материала и имеет детализированную окраску, что делает ее привлекательной для коллекционеров и любителей уникальных игрушек.', 
    categoryId: 4,
    price: 1895,
    rating: 4.7,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p53/p0d/83228774.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/p16/p03/83228777.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p53/p00/83228778.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pea/p09/83228775.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/igrushka-podveska-zootopia-zveropolis-15-sm-mul-tikolor-151137596/?c=750000000',
    likes: 0,
  },
  {
    id:9,
    name: 'Pop Mart Crybaby Series',
    description: 'Pop Mart Crybaby Series - это коллекционная серия фигурок, вдохновленная классическим произведением Антуана де Сент-Экзюпери. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',  
    categoryId: 3,
    price: 2490,
    rating: 4.6,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p54/p21/44135102.jpg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/pc4/p21/44135106.jpg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pa8/p21/44135105.jpg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pe0/p21/44135107.jpg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/igrushka-podveska-pop-mart-crybaby-13-sm-mul-tikolor-140006683/?c=750000000',
    likes: 0,
  },
  {
    id:10,
    name: 'Pop Mart Skullpanda Impressionnisme Series',
    description: 'Pop Mart Skullpanda Impressionnisme Series - это коллекционная серия фигурок, вдохновленная классическим произведением Антуана де Сент-Экзюпери. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',  
    categoryId: 1,
    price: 4990,
    rating: 4,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p2f/pba/57884412.jpg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/p13/pba/57884413.jpg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pe4/p84/57884414.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p7a/p81/57884415.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/pop-mart-skullpanda-impressionnisme-series-13-5-sm-1-sht-143895399/?c=750000000',
    likes: 0,
  },
  {
    id:11,
    name: 'Pop Mart One Piece',
    description: 'Pop Mart One Piece 8 SM 1 Sht - это коллекционная фигурка, вдохновленная популярным аниме-сериалом "One Piece". Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 5,
    price: 15000,
    rating: 0,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p98/pb6/96857673.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/p01/pba/96857674.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p6b/pbd/96857675.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pd5/pc0/96857676.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/pop-mart-the-monsters-one-piece-8-sm-1-sht-154961988/?c=750000000',
    likes: 0,
  },
  {
    id:12,
    name: 'Pop Mart Hirono Little Mischief Series',
    description: 'Pop Mart Hirono Little Mischief Series - это коллекционная серия фигурок. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 2,
    price: 22900,
    rating: 4.9,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/pac/pb0/53791276.png?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/p89/pb3/53791281.png?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pa5/pb3/53791282.png?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p15/pb4/53791286.png?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/pop-mart-pop-mart-kollektsionnaja-figurka-hirono-little-mischief-65389-6-sm-1-sht-142733590/?c=750000000',
    likes: 0,
  },
  {
    id: 13,
    name: 'Игрушка-подвеска Labubu',
    description: 'Labubu - это коллекционная серия фигурок. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 6,
    price: 2436,
    rating: 5,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p8a/pf8/43073542.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/p8a/pf8/43073542.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pb6/pf1/43073544.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p4d/pee/43073545.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/igrushka-podveska-blind-box-17-sm-mul-tikolor-139893450/?c=750000000',
    likes: 0,
  },
  {
    id: 14,
    name: 'Брелок Letsvan Wakuku',
    description: 'Letsvan Wakuku - это коллекционная серия фигурок. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 4,
    price: 1000,
    rating: 5,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/pc2/p69/54540255.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/pc2/p69/54540255.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p2c/p6d/54540254.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p58/p66/54540256.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/igrushka-podveska-letsvan-wakuku-17-sm-mul-tikolor-142929811/?c=750000000',
    likes: 0,
  },
  {
    id: 15,
    name: 'Брелок POP MART Cry baby cat',
    description: 'Cry baby cat - это коллекционная серия фигурок. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 3,
    price: 17499,
    rating: 0,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/pd4/p1e/64391178.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/pd4/p1e/64391178.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p6a/p1b/64391179.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/brelok-pop-mart-cry-baby-cat-12-sm-iskusstvennyi-meh-silikon-6-sht-145531522/?c=750000000',
    likes: 0,
  },
  {
    id: 16,
    name: 'POP MART Hirono shelter',
    description: 'Hirono shelter - это коллекционная серия фигурок. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 2,
    price: 15000,
    rating: 0,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/ped/pef/113705961.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/ped/pef/113705961.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p83/pec/113705962.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pb0/pe5/113705964.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/pop-mart-hirono-shelter-7-sm-1-sht-159267616/?c=750000000',
    likes: 0,
  },
  {
    id: 17,
    name: 'POP MART Labubu – серия Coca-Cola',
    description: 'POP MART Labubu – серия Coca-Cola - это коллекционная серия фигурок. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 6,
    price: 901,
    rating: 4.8,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p54/p53/54227043.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/p54/p53/54227043.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pbe/p56/54227044.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p28/p5a/54227045.jpeg?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/mjagkaja-igrushka-pop-mart-labubu-vinyl-face-plush-serija-coca-cola-17-sm-belyi-korichnevyi-140555755/?c=750000000',
    likes: 0,
  },
  {
    id: 18,
    name: 'Кукла-сюрприз L.O.L. Surprise! Neon Pop Stars',
    description: 'Letsvan Wakuku - это коллекционная серия фигурок. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 7,
    price: 9306,
    rating: 5,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/pb8/pc4/50805933.png?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/pb8/pc4/50805933.png?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pd4/pc4/50805934.png?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pf0/pc4/50805935.png?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/kukla-sjurpriz-l-o-l-surprise-lol-sjurpraiz-neon-pop-stars-43555-8-sm-aksessuary-v-komplekte-ruki-i-nogi-podvizhnye-130722418/?c=750000000',
    likes: 0,
  },
  {
    id: 19,
    name: 'Кукла-сюрприз L.O.L. Surprise!Питомец Шпионы',
    description: 'Letsvan Wakuku - это коллекционная серия фигурок. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 7,
    price: 9899,
    rating: 5,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/pf4/p5c/70743551.png?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/pf4/p5c/70743551.png?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p6b/p5a/70743549.png?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/p10/p5d/70743552.png?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/kukla-sjurpriz-l-o-l-surprise-lol-sjurpraiz-kukla-v-share-pitomets-shpiony-68372-6-sm-aksessuary-v-komplekte-146402800/?c=750000000',
    likes: 0,
  },
  {
    id: 20,
    name: 'Кукла-сюрприз L.O.L. Surprise! Loves Hello Kitty and Friends',
    description: 'Letsvan Wakuku - это коллекционная серия фигурок. Каждая фигурка в этой серии имеет уникальный дизайн и высокое качество исполнения, что делает их особенно ценными для коллекционеров и любителей уникальных аксессуаров.',
    categoryId: 7,
    price: 14294,
    rating: 5,
    image: 'https://resources.cdn-kaspi.kz/img/m/p/p17/p38/53172359.jpeg?format=gallery-medium',
    images: [
      'https://resources.cdn-kaspi.kz/img/m/p/p17/p38/53172359.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pfd/p12/53172360.jpeg?format=gallery-medium',
      'https://resources.cdn-kaspi.kz/img/m/p/pc1/p21/53172361.png?format=gallery-medium',
    ],
    link: 'https://kaspi.kz/shop/p/kukla-sjurpriz-l-o-l-surprise-lol-sjurpraiz-hello-kitty-and-friends-66249-8-sm-aksessuary-v-komplekte-136653302/?c=750000000',
    likes: 0,
  },
  ];

  getCategories(): Category[] {
    return this.categories;
  }

  getProducts(): Product[] {
    return this.products;
  }

  getProductsBycategoryId(categoryIdId: number): Product[] {
    return this.products.filter(p => p.categoryId === categoryIdId);
  }
}